# System configuration file

[data_link]
port = "COM9"

[channel.LC1]
# grams = (adc_reading - offset) * scale
offset = 36000
scale = 0.008871875

[channel.THRM1]
low  = 0x000000  # ADC reading, thermistor shorted
high = 0xffffff  # ADC reading, thermistor disconnected.
r_series = 2000  # Sum of series resistors, in ohms

[channel.THRM2]
# TBD

[channel.THRM3]
# TBD


