# System configuration file
#
# Plot color names are here:
# https://matplotlib.org/stable/gallery/color/named_colors.html

# Semitec thermistors datasheet is here:
# https://www.mouser.com/datasheet/2/362/P18_NT_Thermistor-1535133.pdf

# Calibrated for system #01.

[data_link]
port = "COM4"
#port = "COM9"


[channel.LDC1]
color = "red"
# grams = (adc_reading - adc_offset) * scale
adc_offset = 101470
scale = 0.002671


[channel.TMP1]
color = "blueviolet"
adc = { open = 4196416, short = 220, calib = 466640, calib_r = 250 }
rtd = { r0 = 1000.0, offset=0.00 }


[channel.TMP2]
color = "blue"
adc = { open = 4197817, short = 170, calib = 466648, calib_r = 250 }
thermistor = { beta = 4725, c = 7.06e-8, ref_r = 100000, ref_c = 25, offset=0.00 }


[channel.TMP3]
color = "teal"
adc = { open = 4196623, short = 150, calib = 466460, calib_r = 250 }
thermistor = { beta = 4725, c = 7.06e-8, ref_r = 100000, ref_c = 25 , offset=0.0}


[marker.test_begin]
# Marks the begining of a test.
# Example:
#   [begin:my_test_name-123]
regex = "^begin:(.*)$"
value_group = 1
pen = {color="green", solid=true, width=2}

[marker.test_end]
# Marks the end of a test.
# Example:
#   [end:my_test_name-123]
regex = "^end:(.*)$"
value_group = 1
pen = {color="red", solid=true, width=2}

[marker.poi]
# Marks a general point of interest.
# Examples:
#   [poi]
#   [poi.]
#   [poi.layer-31]
regex = "^poi(:(.*))?$"
value_group = 2
pen = {color="purple", solid=false, width=2}

