# System configuration file

[data_link]
port = "COM9"

[channel.LC1]
# grams = (adc_reading - offset) * scale
offset = 38254
scale = 0.0080

[channel.THRM1]
short_reading = 0x000000   
open_reading  = 0x7fffff    
r_series      = 2000            

[channel.THRM2]
short_reading = 0x000000   
open_reading  = 0x7fffff    
r_series      = 2000   

[channel.THRM3]
short_reading = 0x000000   
open_reading  = 0x7fffff    
r_series      = 2000   


