# System configuration file
#
# Plot color names are here:
# https://matplotlib.org/stable/gallery/color/named_colors.html

# Semitec thermistors datasheet is here:
# https://www.mouser.com/datasheet/2/362/P18_NT_Thermistor-1535133.pdf

[data_link]
port = "COM4"

[channel.LC1]
color = "red"
# grams = (adc_reading - offset) * scale
adc_offset = 101552
scale = 0.002671

[channel.THRM1]
color = "blueviolet"
adc = { open = 4197520, short = 220, calib = 466550, calib_r = 250 }
therm = { beta = 4725, c = 7.06e-8, ref_r = 100000, ref_c = 25 }
# therm = {beta = 4725, c=7.06e-8, ref_r=301.6, ref_c=220}


[channel.THRM2]
color = "blue"
adc = { open = 4195125, short = 170, calib = 466345, calib_r = 250 }
therm = { beta = 4725, c = 7.06e-8, ref_r = 100000, ref_c = 25 }


[channel.THRM3]
color = "teal"
adc = { open = 4196385, short = 150, calib = 466560, calib_r = 250 }
therm = { beta = 4725, c = 7.06e-8, ref_r = 100000, ref_c = 25 }
